name: pakka_homes
description: Pakka Homes Flutter app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/plumbing.png
    - assets/electrical.png
    - assets/cleaning.png
    - assets/painting.png
    - assets/waterproofing.png
    - assets/repair.png
    - assets/services/construction/
    - assets/services/electrical/
    - assets/services/cleaning/
    - assets/services/mason/
    - assets/services/appliance-repair/
    - assets/services/plumbing/
    - assets/services/painting/
    - assets/services/carpenter/
    - assets/services/waterproofing/
    - assets/services/interior/
    - assets/shop/cement/
    - assets/shop/electricals/
    - assets/shop/sanitaryware/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/main icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/main icon/app_icon_foreground.png"
  min_sdk_android: 21
